# Generated by Django 3.0 on 2019-12-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('latitude', models.FloatField(help_text='(Required) Latitude coordinate for squirrel sighting point')),
                ('longitude', models.FloatField(help_text='(Required) Longitude coordinate for squirrel sighting point')),
                ('unique_squirrel_id', models.CharField(help_text='(Required) Identification tag for each squirrel sightings. The tag is comprised of "Hectare ID" + "Shift" + "Date" + "Hectare Squirrel Number."', max_length=50, primary_key=True, serialize=False)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='(Required) Value is either "AM" or "PM," to communicate whether or not the sighting session occurred in the morning or late afternoon.', max_length=10)),
                ('date', models.DateField(help_text='(Required) Concatenation of the sighting session day and month.')),
                ('age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Value is either "Adult" or "Juvenile."', max_length=20, null=True)),
                ('primary_fur_color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Value is either "Gray," "Cinnamon" or "Black."', max_length=20, null=True)),
                ('location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Value is either "Ground Plane" or "Above Ground." Sighters were instructed to indicate the location of where the squirrel was when first sighted.', max_length=20, null=True)),
                ('specific_location', models.TextField(blank=True, help_text='Sighters occasionally added commentary on the squirrel location. These notes are provided here.', null=True)),
                ('running', models.BooleanField(help_text='Whether the squirrel is running')),
                ('chasing', models.BooleanField(help_text='Whether the squirrel is chasing')),
                ('climbing', models.BooleanField(help_text='Whether the squirrel is climbing')),
                ('eating', models.BooleanField(help_text='Whether the squirrel is eating')),
                ('foraging', models.BooleanField(help_text='Whether the squirrel is foraging')),
                ('other_activities', models.TextField(blank=True, help_text='Other activities the squirrel is conducting', null=True)),
                ('kuks', models.BooleanField(help_text='Squirrel was heard kukking, a chirpy vocal communication used for a variety of reasons.')),
                ('quaas', models.BooleanField(help_text='Squirrel was heard quaaing, an elongated vocal communication which can indicate the presence of a ground predator such as a dog.')),
                ('moans', models.BooleanField(help_text='Squirrel was heard moaning, a high-pitched vocal communication which can indicate the presence of an air predator such as a hawk.')),
                ('tail_flags', models.BooleanField(help_text="Squirrel was seen flagging its tail. Flagging is a whipping motion used to exaggerate squirrel's size and confuse rivals or predators. Looks as if the squirrel is scribbling with tail into the air.")),
                ('tail_twitches', models.BooleanField(help_text='Squirrel was seen twitching its tail. Looks like a wave running through the tail, like a breakdancer doing the arm wave. Often used to communicate interest, curiosity.')),
                ('approaches', models.BooleanField(help_text='Squirrel was seen approaching human, seeking food.')),
                ('indifferent', models.BooleanField(help_text='Squirrel was indifferent to human presence.')),
                ('runs_from', models.BooleanField(help_text='Squirrel was seen running from humans, seeing them as a threat.')),
            ],
        ),
    ]
